### ISSUE TITLE
Card broken

### ISSUE THREAD

**Issue by w1tw0lf** [t1gr0u/uv-index-card#1]
The card seems to be broken.

This is all that is in the .js file
`export{U as UVIndexCard}from"./uv-index-card-0fcdad5c.js";`

When adding to dashboard, I get this:
![image](https://user-images.githubusercontent.com/55384762/229336931-a9bbf699-de4e-4766-b83b-95cbb3793765.png)

**Comment by t1gr0u** [comment]
@w1tw0lf thank you for letting me know :)
I will try and fix this asap

**Comment by t1gr0u** [comment]
@w1tw0lf This is now fixed in v1.1.0

Thank you again for pointing this out 👍
