### ISSUE TITLE
Auto resize the pyramid image or provide a different, smaller scale (vertical bar?) when displaying the UV index in a smaller tile

### ISSUE THREAD

**Issue by ThatTallGuy21** [t1gr0u/uv-index-card#11]
When including UV details in a smaller tile (ex: vertical-stack 2 grid column), it would be nice if either the pyramid resized to be smaller or a different image could be displayed so the text didn't overlap the image.

![Screenshot 2023-05-07 075554](https://user-images.githubusercontent.com/86063203/236676287-105787b1-4ad0-4c2f-89d7-ab39fe5d33e0.png)

**Comment by t1gr0u** [comment]
This is now fixed in v1.2.0
