### ISSUE TITLE
Entity precision ignored

### ISSUE THREAD

**Issue by WoBBeLnl** [t1gr0u/uv-index-card#13]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 1.10 & 1.2.0

**Last working release (if known):** None

**Browser and Operating System:** Multiple systems/browsers including Android Companion App

**Description of problem:**

The precision set for my Max UV Index (see screenshots) gets ignored by the UV index card. I have rounded the entity but it still shows on the card,  HA itself shows it rounded to 1 decimal (as configured).

![uv1](https://github.com/t1gr0u/uv-index-card/assets/3839789/663c8390-db10-4b38-8c12-96f77750ebf4)
![uv2](https://github.com/t1gr0u/uv-index-card/assets/3839789/560b5d4c-9445-460d-9ca1-997796212673)

**Comment by t1gr0u** [comment]
@WoBBeLnl the card doesn't manipulate the entity, it display what it receives.
How do you set the precision on the entity?
Do you set a new entity?
What value do you get when viewing the entity in the `developer tools` --> `states`?

**Comment by WoBBeLnl** [comment]
How do you set the precision on the entity?
- I've set it via Settings -> Devices & Services -> Entities -> click on entity -> change entity -> set precision (see screenshot)

Do you set a new entity?
- No, I've set the precision for the "Max UV Index". This entity is added/updated by the "OpenUV" integration.

What value do you get when viewing the entity in the developer tools --> states?
- It shows the exact state, ignoring my display precision setting. (see screenshot)

I've added a few screenshots chaning my HA to English.

https://developers.home-assistant.io/blog/2023/02/08/sensor_presentation_rounding 
Released 2023.2 https://www.home-assistant.io/blog/2023/02/01/release-20232/
Some more info https://www.home-assistant.io/blog/2023/03/01/release-20233/#sensor-display-precision

Not sure how a addon works, but with templating you can choose to use the rounding.
https://www.home-assistant.io/docs/configuration/templating/#formatting-sensor-states

![entity_configuration](https://github.com/t1gr0u/uv-index-card/assets/3839789/2d16ffd5-1446-4210-a68d-e0d6500f37f1)
![states](https://github.com/t1gr0u/uv-index-card/assets/3839789/21671f61-0e02-44ed-ae64-bef8d1b8e8b4)

**Comment by t1gr0u** [comment]
@WoBBeLnl thank you will try and have a look :)

**Comment by t1gr0u** [comment]
@WoBBeLnl I had a look and here are my findings:
I installed the OpenUV integration and added precision to the `Max UV Index`
<img width="561" alt="Screenshot 2023-05-10 at 21 52 49" src="https://github.com/t1gr0u/uv-index-card/assets/1346793/75738d44-45e1-4a72-87e4-fa0d153ae536">

Then added some debug to the code and this is what I get back from the entity:
<img width="1033" alt="Screenshot 2023-05-10 at 21 52 14" src="https://github.com/t1gr0u/uv-index-card/assets/1346793/7795e659-f82c-4def-be06-6043b9ef941d">

As you can see, the precision value is not returned :( and I haven't got a way to get this value.

**Comment by WoBBeLnl** [comment]
Ah thats a bummer. HA is not providing, thats a bummer.
