### ISSUE TITLE
Possibility to change color

### ISSUE THREAD

**Issue by Desaydrone** [t1gr0u/uv-index-card#20]
Hi,

May be i miss how to do that, but it could be interesting to have options to change color of every uv level.

This will allow to keep a homogeneity in the themes

**Comment by t1gr0u** [comment]
@Desaydrone To be honest all the colours that I've used are the ones that most UV index gauges are using.

If I get more interest in this then I could implement this.

**Comment by Desaydrone** [comment]
No problem i edit manually the files to do the change :)
