### ISSUE TITLE
how to select the language of the card

### ISSUE THREAD

**Issue by SiriosDev** [t1gr0u/uv-index-card#3]
I saw the language section and I would like to understand if they can be selected or change according to HA.

**Comment by SiriosDev** [comment]
not a bug but not a fr either, so it's pretty indifferent to choose between the two

**Comment by WoBBeLnl** [comment]
It would be nice to manually set the language (optional) instead of auto selecting it.

**Comment by t1gr0u** [comment]
@SiriosDev at the moment, the plugin will take the language that you have selected under your profil.

I could have a look at in forcing the language instead of using the HA's language.

**Comment by t1gr0u** [comment]
This is now added in v1.2.0
