### ISSUE TITLE
[Question] Reuse/copy card for PM2.5

### ISSUE THREAD

**Issue by MelleD** [t1gr0u/uv-index-card#34]
Hello,

I already use your card for the UV index and I really like it.
I think the card would also suit the PM 2.5 values ​​quite well to display them:
Please refer:
https://www.iqair.com/de/newsroom/how-to-monitor-outdoor-air-quality

Would you be okay with me copying and adapting your card to adjust the values for the PM2.5?

What do you think? Do you have another idea?

Thanks

**Comment by t1gr0u** [comment]
Hi @MelleD ,
more than welcome to copy and adapt the card.
Maybe reference the UV card in the Readme?

This sounds a really good idea 👍 
Let me know when you have finished, keen to see it working.

If you need a hand, give a shout :)

**Comment by MelleD** [comment]
Hi @t1gr0u,

thanks for the quick answer. 

> more than welcome to copy and adapt the card.

Cool thanks a lot 👍 

> Maybe reference the UV card in the Readme?

It's the least I can do

> If you need a hand, give a shout :)

Thanks :)

**Comment by MelleD** [comment]
Hey @t1gr0u,

here we go https://github.com/MelleD/pm-index-card

![Bildschirmfoto 2024-01-31 um 09 51 10](https://github.com/t1gr0u/uv-index-card/assets/6340898/ebc4af0d-1825-40d6-94e3-6dc7d7b79bc8)

Coloring is not working correct, but the rest was really easy to adapt. Good job 👍 

If you have any feedback, welcome and ping me :)

**Comment by t1gr0u** [comment]
@MelleD looks really nice, good job 👍
