### ISSUE TITLE
Horizontal stack resize

### ISSUE THREAD

**Issue by Psytoshgen** [t1gr0u/uv-index-card#4]
Hi,
Found that resize not correct in phone mode. Also entity selector don't give to write entity, only select from list.

![image](https://user-images.githubusercontent.com/94195788/235580829-dd68b9a2-0a7b-4d75-826f-0a5904086203.png)![image](https://user-images.githubusercontent.com/94195788/235580973-7c4c8e68-96de-4759-9677-e4c6a9cf7d88.png)

**Comment by ThatTallGuy21** [comment]
![Screenshot 2023-05-07 075554](https://user-images.githubusercontent.com/86063203/236675940-199d74fd-d94c-4d4d-a2b4-3877e65f0f2e.png)

Noticing the same thing in my vertical-stack 2 column grid on my desktop browser as well.

**Comment by t1gr0u** [comment]
This is now fixed in v1.2.0
